swagger: '2.0'
info:
  description: This is DataHub API.
  version: "v1"
  title: Datahub API

  contact:
    email: dataportal-edirex@ics.muni.cz

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html


paths:
  /patients:
    get:
      summary: searches patients
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Patient'
  /pdxmodels:
    get:
      summary: searches pdxmodels
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/PDXmodel'
  /cnas:
    get:
      summary: searches cnas
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Cnas'
  /expressions:
    get:
      summary: searches expressions
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Expressions'
  /mutations:
    get:
      summary: searches mutation records
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Mutation'
  /metafiles:
    get:
      summary: searches metafiles records
      produces:
        - applicaiton/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/MetaFile'
  /metafiles/{study_name}:
    get:
      summary: returns metafiles for concrete study
      parameters:
      - name: "study_name"
        in: "path"
        required: true
        type: "string"
      produces:
        - applicaiton/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/MetaFile'
  /pdxmodels/{model_id}:
    get:
      summary: returns specific pdxmodel
      parameters:
      - name: "model_id"
        in: "path"
        required: true
        type: "string"
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/PDXmodel'
  /pdxmodels/{model_id}/cnas:
    get:
      summary: searches cna records for specific PDXmodel
      parameters:
      - name: "model_id"
        in: "path"
        required: true
        type: "string"
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Cnas'
  /pdxmodels/{model_id}/expressions:
    get:
      summary: searches expression records for specific pdxmodel
      parameters:
      - name: "model_id"
        in: "path"
        required: true
        type: "string"
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Expressions'
  /pdxmodels/{model_id}/mutations:
    get:
      summary: searches mutation records for specific PDXmodel
      parameters:
      - name: "model_id"
        in: "path"
        required: true
        type: "string"
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Mutations'
  /studies:
    get:
      summary: list all avaible studies
      produces:
        - application/json
      responses:
        200:
          description: search results
          schema:
            type: array
            items:
              $ref: '#/definitions/Study'
  /studies/{study_name}/pdxmodels:
    get:
      summary: list pdxmodels for specific studies
      parameters:
      - name: "study_name"
        in: "path"
        required: true
        type: "string"
      produces:
        - application/json
      responses:
        200:
          description: search results mathing criteria, returns studies with pdxmodels
          schema:
              $ref: '#/definitions/StudyWithPDXmodels'
  /studies/{study_name}/cancertypes:
    get:
      summary: List available cancer types for specific study
      parameters:
      - name: "study_name"
        in: "path"
        required: true
        type: "string"
      produces:
        - application/json
      responses:
        200:
          description: List of available cancer types
          schema:
            type: array
            items:
              $ref: '#/definitions/CancerType'
  /studies/{study_name}/cnas/{stable_id}:
    get:
      summary: List of avaible cnas for specific study, by specific stableID. Gisitic is set as default
      parameters:
        - name: "study_name"
          in: "path"
          required: true
          type: "string"
        - name: "stable_id"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: List of available cnas
          schema:
            type: array
            items:
              $ref: '#/definitions/Cnas'
  /studies/{study_name}/expressions/{stable_id}:
    get:
      summary: List of avaible expressions for specific study, by specific stableID. rna_seq_mrna is set as default
      parameters:
        - name: "study_name"
          in: "path"
          required: true
          type: "string"
        - name: "stable_id"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: List of available expressions
          schema:
            type: array
            items:
              $ref: '#/definitions/Expressions' 
  /studies/{study_name}/mutations:
    get:
      summary: List of avaible mutations for specific study.
      parameters:
        - name: "study_name"
          in: "path"
          required: true
          type: "string"
      responses:
        200:
          description: List of available Mutations
          schema:
            type: array
            items:
              $ref: '#/definitions/Mutations'
  /cancertypes:
    get:
      summary: List available cancer types
      produces:
        - application/json
      responses:
        200:
          description: List of available cancer types
          schema:
            type: array
            items:
              $ref: '#/definitions/CancerType'
  /tmplists:
    get:
      summary: Get all of the temporary stored lists of pdxmodels
      produces:
        - application/json
      responses:
        200:
          description: Return list of lists ids.
          schema:
            type: array
            items:
              $ref: '#/definitions/Tmplist'
    post:
      summary: Upload list of pdxmodel ids
      description: >
        Simple usage: 
          curl -X POST -d '{"pdxmodel_list":["value1","value2","value3"]}' -H "Content-Type: application/json" https://hostname/api/v1/tmplists
        
      produces:
        - application/json
      parameters:
      - name: pdxmodels
        in: body
        required: true
        description: List of pdxmodels ids to store.
        schema:
          $ref: '#/definitions/PostTmpList'
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/TmpListId'

  /tmplists/{list_id}:
    get:
      summary: Store and access temporary created lists of pdxmodels
      parameters:
      - name: "list_id"
        in: "path"
        required: true
        type: "string"
      produces:
        - application/json
      responses:
        200:
          description: Return list of pdxmodel ids.
          schema:
            type: array
            items:
              type: string
              example: CRC0691LM
  /tmplists/{list_id}/pdxmodels:
    get:
      summary: Return pdxmodels records 
      parameters:
      - name: "list_id"
        in: "path"
        required: true
        type: "string"
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/PDXmodel'

  /tmplists/{list_id}/cnas:
    get:
      summary: Return cna records 
      parameters:
      - name: "list_id"
        in: "path"
        required: true
        type: "string"
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Cnas'
  /tmplists/{list_id}/expressions:
    get:
      summary: Return cna records 
      parameters:
      - name: "list_id"
        in: "path"
        required: true
        type: "string"
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Expressions'
  /tmplists/{list_id}/mutations:
    get:
      summary: Return cna records 
      parameters:
      - name: "list_id"
        in: "path"
        required: true
        type: "string"
      produces:
        - application/json
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Mutations'
  /tmplists/{list_id}/statistics:
    get:
      summary: Provide statistical occurancy of avaible data for models in studies
      parameters:
      - name: "list_id"
        in: "path"
        required: true
        type: "string"
        description: /tmplists/1/statistics
      produces:
        - application/json
      responses: 
        200:
          description: statistic for models in studies
          schema:
            type: array
            items:
              $ref: '#/definitions/Statistics'
definitions:
  Statistics:
    type: object
    properties:
      study:
        type: string
        example: IRCC
      samples:
        type: string
        example: 700
      expressions:
        type: array
        items:
          $ref: '#/definitions/stats'
      cnas:
        type: array
        items:
          $ref: '#/definitions/stats'
      muts:
        type: array
        items:
          $ref: '#/definitions/stats'
  stats:
    type: object
    properties:
      stable_id:
        type: string
        example: gistic
      count: 
        type: string
        example: 10
  Patient:
    type: object
    required:
    - patient_id
    properties:
      patient_id:
        type: string
        example: 11111000206
      first_diagnoses:
        type: string
        example: "colorectal carcinom"
      sex:
        type: string
        enum: ["male","female", "not specified"]
        example: "female"
  PDXmodel:
    type: object
    properties:
      model_id:
        type: string
        example: CRC0691LM
      patient_id:
        type: string
        example: 'GTR0009'
      institution:
        type: string
        example: 'UNITO'
      date_of_collection:
        type: string
        example: 'Oct 2014'
      age_at_collection:
        type: string
        example: '55'
      sample_origin:
        type: string
        example: 'Primary'
      site_of_sampled_metastasis:
        type: string
        example: 'axillary'
      engrafment_site:
        type: string
        example: 'interscapular fat pad'
      engrafment_type:
        type: string
        example: 'heterotopic'
      engrafment_material:
        type: string
        example: 'tissue fragment'
      strain:
        type: string
        example: 'NMRI nude'
      site_of_primary:
        type: string
        example: 'breast'
      cancer_study_identifier:
        type: string
      MS_status:
        type: string
        example: 'stable'
        enum: ['stable','instable']
      sample_class:
        type: string
        
        
  Cna:
    type: object
    properties:
      entrez_gene_id:
        type: integer
        example: 1
      value:
        type: integer
        example: 2
  Cnas:
    type: object
    properties:
      pdxmodel_id:
        type: string
        example: "CRC0691LM"
      sample_id:
        type: string
        example: "CRC0691LMX0A01…"
      stable_id:
        type: string
        example: gistic
      cnas:
        type: array
        items:
          $ref: '#/definitions/Cna'
  Expression:
    type: object
    properties:
      hugo_symbol:
        type: string
        example: ABCA12
      entrez_gene_id:
        type: integer
        example: 100132074
      value:
        type: integer
        example: 2
  Expressions:
    type: object
    properties:
      pdxmodel_id:
        type: string
        example: CRC0691LM
      sample_id:
        type: string
        example: "CRC0691LMX0A01…"
      stable_id:
        type: string
        example: rna_seq_mrna
      expressions:
        type: array
        items:
          $ref: '#/definitions/Expression'
  Mutation:
    type: object
    properties:
      entrez_gene_id:
        type: integer
        example: 100132074
      ncbiBuild:
        type: number
        example: 37.1
      chromosome:
        type: integer
        example: 12
      startPosition:
        type: integer
        example: 9243799
      endPosition:
        type: integer
        example: 9243799
      strand:
        type: integer
        example: -1
      variantClassification:
        type: string
        example: Missense_Mutation
      hgvsShort:
        type: string
        example: p.R823W
      proteinPosition:
        type: integer
        example: 823
      swissprot:
        type: string
        example: A0A0A0MT16
  Mutations:
    type: object
    properties:
      pdxmodel_id:
        type: string
        example: CRC0691LM
      sample_id:
        type: string
        example: "CRC0691LMX0A01…"
      mutations:
        type: array
        items:
          $ref: '#/definitions/Mutation'
  MetaFile:
    type: object
    required:
    - genetic_alteration_type
    - datatype
    - stable_id
    - show_profile_in_analysis_tab
    - profile_description
    - profile_name
    - swissprot_identifier
    - data_filename
    properties:
      genetic_alteration_type:
        type: string
        example: MUTATION_EXTENDED
      datatype:
        type: string
        example: MAF
      stable_id:
        type: string
        example: mutations
      show_profile_in_analysis_tab:
        type: string
        example: true
      profile_description:
        type: string 
        example: Mutation data
      profile_name:
        type: string 
        example: Mutations
      swissprot_identifier:
        type: string 
        example: accession
      data_filename:
        type: string
        example: mutations_extended.maf
  Study:
    type: object
    required:
    - cancer_study_identifier
    - cancer_type_id
    - description
    - short_name
    properties:
      cancer_study_identifier:
        type: string
        example: ircc_crc_feb2018
      cancer_type_id:
        type: integer
        example: 1234
      description:
        type: string
        example: 500 colorectal cancer models (ircc)
      short_name:
        type: string
        example: IRCC CRC
  StudyWithPDXmodels:
    type: object
    required:
    - studies
    - pdxmodels
    properties:
      studies:
          $ref:  '#/definitions/Study'
      pdxmodels:
        type: array
        items:
          $ref: '#/definitions/PDXmodel'
  CancerType:
    type: object
    properties:
      oncotree_code:
        type: string
        example: crc
      name:
        type: string
        example: Colorectal cancer
      description:
        type: string
        example: colorectal,colon
      dedicated_color:
        type: string
        example: tomato
      parent_type_of_cancer:
        type: string
        example: tissue
  TmpListId:
    type: object
    required:
    - tmplistid
    properties:
      tmplistid:
        type: string
        example: "1234"
  PostTmpList:
    type: object
    properties:
      pdxmodel_list:
        type: array
        items: 
          type: string
          example: [CRC0691LM, CRC0666LM]
  Tmplist:
    type: object
    properties:
      tmp_list_id:
        type: integer
        example: 3
      pdxmodel_ids:
        type: array
        items:
          type: string
          example: CRC0691LM
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /RadimPesa/datahub/v1
schemes:
 - https